export enum HomeRecipeRelations {
  HOME = 'home',
  SYSTEM_INFO = 'system-info',
  REGISTER = 'create-a-user',
  LOGIN = 'login',
  LOGOUT = 'logout',
  USER = 'get-user-by-id',
  AUTH_HOME = 'auth-home',
  RANKING_INFO = 'ranking-info',
  USER_STATS = 'get-user-stats',
  USER_STATS_BY_USERNAME = 'get-user-stats-by-username',
  UPDATE_USER = 'update-user',
  GAME = 'get-game-by-id',
  PLAY = 'play',
  MATCHMAKING = 'matchmaking',
  MATCHMAKING_STATUS = 'get-matchmaking-status',
  LEAVE = 'leave',
  GET_ALL_GAMES = 'get-all-games',
  GET_ALL_GAMES_BY_USER = 'get-all-games-by-user',
  EXIT_MATCHMAKING_QUEUE = 'exit-matchmaking-queue',
  GET_ALL_VARIANTS = 'get-all-variants',
}
